"""initial app config schema with bigint org_id

Revision ID: 2a4e35a7502c
Revises: 
Create Date: 2026-09-17 12:43:12.858737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a4e35a7502c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1000000000, increment=1), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='clientstatus'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id BETWEEN 1000000000 AND 9999999999', name='ck_clients_id_10_digits'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uix_name')
    )
    op.create_table('connectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('API', 'CSV', 'S3', name='connectortype'), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('api_secret', sa.String(), nullable=False),
    sa.Column('field_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notification_email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('org_id BETWEEN 1000000000 AND 9999999999', name='ck_connectors_org_id_10_digits'),
    sa.ForeignKeyConstraint(['org_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('reporting_manager_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('org_id IS NULL OR org_id BETWEEN 1000000000 AND 9999999999', name='ck_users_org_id_10_digits'),
    sa.ForeignKeyConstraint(['org_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uix_email'),
    sa.UniqueConstraint('org_id', 'username', name='uix_org_id_username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('connectors')
    op.drop_table('roles')
    op.drop_table('clients')
    # ### end Alembic commands ###
