"""add connection_config to connectors

Revision ID: 6b4ddb8d8bfc
Revises: 78ec4d2422a1
Create Date: 2026-09-28 16:49:55.062794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b4ddb8d8bfc'
down_revision: Union[str, Sequence[str], None] = '78ec4d2422a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connectors', sa.Column('connection_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connectors', 'connection_config')
    # ### end Alembic commands ###
