"""create connectors table

Revision ID: 94c9ae33c54c
Revises: 4cbb7c2e567a
Create Date: 2026-08-26 18:27:32.984270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94c9ae33c54c'
down_revision: Union[str, Sequence[str], None] = '4cbb7c2e567a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('API', 'CSV', 'S3', name='connectortype'), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('api_secret', sa.String(), nullable=False),
    sa.Column('field_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notification_email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connectors')
    # ### end Alembic commands ###
