"""create lead_ingestion_batches table

Revision ID: 1f5ceb427eb3
Revises: 6c42aa1ac577
Create Date: 2026-09-09 13:08:02.116022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = '1f5ceb427eb3'
down_revision: Union[str, Sequence[str], None] = '6c42aa1ac577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_ingestion_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PROCESSING', 'COMPLETED_SUCCESSFULLY', 'COMPLETED_WITH_ERRORS', 'FAILED', 'PENDING', name='leadingestionbatchstatus'), nullable=False),
    sa.Column('source',ENUM('API', 'CSV', 'S3', name='leadsource', create_type=False),nullable=False,),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('total_leads', sa.Integer(), nullable=False),
    sa.Column('success_leads', sa.Integer(), nullable=False),
    sa.Column('failed_leads', sa.Integer(), nullable=False),
    sa.Column('error_messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_ingestion_batches')
    # ### end Alembic commands ###
